[[shades]]
name = "vibrance"
default = true  # shader to use during times when there is no other shader scheduled

[[shades]]
name = "blue-light-filter"
start_time = 01:00:00
end_time = 01:00:01   # optional if you have more than one shade with start_time
